### ISSUE TITLE
the preview fires twice

### ISSUE THREAD

**Issue by alexbodn** [deadlyjack/Acode#918]
hello friend,

a huge thank for acode overall. it's a great tool to write software on the go.

when pressing the ▶️ button on either html or js files, the file loads.

but when pressing back 🔙 i see the same file loaded in another window: browser for html, or console for js.

since the development is in a phone, i assume there're not plenty of resources to waste.

could this be resolved?

thanks in advance,

alex

**Comment by deadlyjack** [comment]
Fixed in v1.9.0

**Comment by alexbodn** [comment]
thanks @deadlyjack for considering my report.
i have 1.9.0 (931), with this problem still active.

**Comment by alexbodn** [comment]
it was indeed fixed in a later commit of 1.9.0 and it works much faster now.
thank you very much friend.
